### PR TITLE
Merge changes from dev to production.

### PR DESCRIPTION
**Pull request by bubby932**
This should resolve some security advisories and bring the code base significantly closer up to date.
It also removes WSv1.

### CODE REVIEW

**Review by 9021007 — COMMENTED** [review]
gud 👍

**Comment by bubby932** [comment]
i merged this an hour ago

**Comment by 9021007** [comment]
Skill issue ngl

**Comment by bubby932** [comment]
which one of us probably woke up 5 minutes ago

**Comment by 9021007** [comment]
Stfu I woke up at the crack of dawn

2:45pm

**Comment by bubby932** [comment]
truly a you moment

**Pull request merged**
